<h1><?php echo "Crear usuario"; ?></h1>
<hr>
<style>
    label{
        width: 100%;
        padding-bottom: 20px
    }
</style>

<?php
$form =  $this->form;
$form->prepare();

$form->setAttributes(array(
        "action" => "",
        "method" => "post"
));
//Para mostrar el Label
$formLabel = $this->plugin("formLabel");
//Pintar la etiqueta de apertura del formulario
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>



