<h1><?php echo $this->lowercase("  ".$this->title) ; ?></h1>
<?php
$form =  $this->form;
$form->prepare();

$form->setAttributes(array(
        //"action" => $this->basePath()."/application/index/get-date-form",
        //"action" => $this->basePath()."/get-form",
        "action" => "",
        "method" => "post"
));
//Para mostrar el Label
$formLabel = $this->plugin("formLabel");
//Pintar la etiqueta de apertura del formulario
echo $this->form()->openTag($form);
?>


<div class="form-element">
        <?php
                $nombre = $form->get("nombre");
                echo $formLabel->openTag().$nombre->getOption("label")." ";
                echo $this->formInput($nombre);
                echo $formLabel->closeTag();
        ?>
</div>

<div class="form-element">
        <?php
                $email = $form->get("email");
                echo $formLabel->openTag().$email->getOption("label")." ";
                echo $this->formInput($email);
                echo $formLabel->closeTag();
        ?>
</div>

<div class="form-element">
        <?php
                $activo = $form->get("activo");
                echo $formLabel->openTag().$activo->getOption("label")." ";
                echo $this->formSelect($activo);
                echo $formLabel->closeTag();
        ?>
</div>

<div class="form-element estado">
        <?php
                $estado = $form->get("estado");
                echo "".$this->formRadio($estado);
        ?>
</div>

<?php 
$documento = $form->get('documento');
echo "<label for='documento'>".$this->formElement($documento)."Documento</label>";
echo "</br>";
//echo "Nombre: ".$this->formElement($form->get("nombre"));
//echo "Email: ".$this->formElement($form->get("email"));
//echo "Activo: ".$this->formSelect($form->get("activo"));
echo $this->formElement($form->get("submit"));
?>


<?php 
//echo $this->formCollection($form);
?>

<?php
echo $this->form()->closeTag();
?>
